# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# Detect if we have an interactive shell
if [[ -n "$PS1" ]]; then
    # <-------------- Interactive section -----------------------> #

    # load the group's modules
    if hash module 2> /dev/null ; then
    
	    source /well/sansom/shared/modules/v2/modules.sh
	    
    fi
	 
    # User specific aliases and functions, e.g.
    alias t='tmux attach || tmux'
    alias s="sqlite3 -header csvdb"
    alias qw="watch qstat -u $USER" 
    alias whois="ls /well/sansom/users/ | xargs getent passwd"
    
    ## example of a function definition to source a python venv
    # venv() {
    #   source ~/devel/venvs/python-3.8.2-GCCcore-9.3.0-skylake/bin/activate
    #   }
    
    ## SLURM configuration
    export SLURM_CONF=/run/slurm/conf/slurm.conf
    export DRMAA_LIBRARY_PATH=/usr/lib64/libdrmaa.so 

    ## Alternative set up for UGE (comment out the two lines above)
    # export DRMAA_LIBRARY_PATH=/mgmt/uge/8.6.8/lib/lx-amd64/libdrmaa.so.1.0

    ## Allow seperate processes to perform concurrent reads from hdf5 files.
    export HDF5_USE_FILE_LOCKING=FALSE

fi
